### ISSUE TITLE
the processed version (includes dependency and temporal graphs of each document) of NYT and APW datasets.

### ISSUE THREAD

**Issue by ChaoYue0307** [malllabiisc/NeuralDater#2]
After unzipping the nyt.zip and apw.zip, I only got nyt_data_preprocessed.pkl and apw_data_preprocessed.pkl and not find any dependency and temporal graph files, what should I do to get them? Thanks

**Comment by svjan5** [comment]
Hi @ChaoYue0307,
As already explained in `Readme.md`, the value corresponding to "DepEdges" and "ETEdges" contain dependency and temporal graph edges respectively.
